Repository apache/kvrocks, pull requests merged in 2021-11, with the labels that each got.

#381 Implement zrevrangebylex command
  src/redis_cmd.cc
  src/redis_zset.cc
  src/redis_zset.h
  tests/t_zset_test.cc
  tests/tcl/tests/unit/command.tcl
  tests/tcl/tests/unit/type/zset.tcl
Labels: new feature, release notes

#387 Add rocksdb ops statistics in info cmd
  src/server.cc
  src/server.h
  src/stats.h
  tests/tcl/tests/unit/command.tcl
Labels: enhancement

#390 Move some docs to wiki and update the links
  README.md
  docs/multi-tenant.CN.md
  docs/support-commands.md
Labels: documentation

#396 Add write stall stats to info command output
  src/server.cc
Labels: release notes

#395 Add some rocksdb new feature
  kvrocks.conf
  src/config.cc
  src/config.h
  src/server.cc
  src/storage.cc
  src/storage.h
  tests/config_test.cc
Labels: release notes
