Repository apache/kvrocks, pull requests merged in 2021-02, with the labels that each got.

#174 Fix subscribe and unsubscribe command and pattern mode
  src/redis_cmd.cc
  src/redis_connection.cc
  src/redis_connection.h
Labels: release notes

#175 Fix reply content for pattern subscribers when publish message
  src/server.cc
  tests/functional/pub_sub_test.py
Labels: release notes

#193 Fix using the line as error msg which has freed
  src/replication.cc
Labels: bug

#194 Feature/add flushbackup command
  kvrocks.conf
  src/redis_cmd.cc
  src/server.cc
  src/server.h
  src/storage.cc
Labels: enhancement, release notes
