Repository apache/kvrocks, pull requests merged in 2021-05, with the labels that each got.

#247 Use reference to avoid creating a copy in for loop
  src/redis_cmd.cc
  src/redis_set.cc
  src/worker.cc
Labels: enhancement

#248 Refactor the Redis command table to support attributes
  src/main.cc
  src/redis_cmd.cc
  src/redis_cmd.h
Labels: enhancement

#253 Fix data race for accessing database in some commands
  src/redis_set.cc
  src/redis_zset.cc
  src/server.cc
  src/worker.cc
Labels: bug, enhancement, release notes

#251 Support COMMAND command
  src/redis_cmd.cc
  src/server.cc
  src/server.h
  tests/tcl/runtest
  tests/tcl/tests/test_helper.tcl
  tests/tcl/tests/unit/command.tcl
Labels: new feature, release notes

#264 Allow to run the kvrocks without assigning the config file
  src/config.cc
  src/config.h
  src/main.cc
Labels: enhancement

#272 Add rename-command config
  kvrocks.conf
  src/config.cc
  src/config.h
  src/main.cc
  src/redis_cmd.cc
  src/redis_cmd.h
  src/server.cc
  src/server.h
  tests/tcl/tests/test_helper.tcl
  tests/tcl/tests/unit/config.tcl
Labels: new feature, release notes

#278 Refactor db mutex
  src/compact_filter.cc
  src/compaction_checker.cc
  src/rw_lock.h
  src/server.cc
  src/server.h
  src/storage.cc
  src/storage.h
  tests/rwlock_test.cc
Labels: major decision
