Repository apache/kvrocks, pull requests merged in 2021-12, with the labels that each got.

#415 Implement CAS and CAD commands for string type
  src/redis_cmd.cc
  src/redis_string.cc
  src/redis_string.h
  tests/t_string_test.cc
  tests/tcl/tests/unit/command.tcl
  tests/tcl/tests/unit/type/string.tcl
Labels: release notes

#418 Adjust the max open file limit according to the max clients and rocksdb max open files
  src/config.cc
  src/server.cc
  src/server.h
Labels: release notes

#407 Support to use row cache of RocksDB
  kvrocks.conf
  src/config.cc
  src/config.h
  src/storage.cc
  tests/config_test.cc
Labels: release notes, major decision

#440 Fix data race in `SetCurrentConnection`
  src/redis_connection.cc
Labels: bug, release notes
