Repository apache/kvrocks, pull requests merged in 2021-07, with the labels that each got.

#314 Fix LTRIM only delete first item, LREM cannot correctly remove repeated items
  src/redis_cmd.cc
  src/redis_list.cc
  tests/t_list_test.cc
  tests/tcl/tests/unit/type/list.tcl
Labels: bug, need back patch, release notes

#331 Use the rocksdb MultiGet in the MGet command
  src/redis_bitmap.cc
  src/redis_db.cc
  src/redis_list.cc
  src/redis_metadata.h
  src/redis_reply.cc
  src/redis_set.cc
  src/redis_string.cc
  src/redis_string.h
Labels: enhancement

#334 Supplements of guideline of compilation on macOS with make and clean up some code
  README.md
  src/redis_cmd.cc
  src/redis_db.cc
  src/redis_hash.cc
  src/util.cc
Labels: documentation, enhancement

#337 Fix SETNX and MSETNX commands can't guarantee atomicity
  src/redis_cmd.cc
  src/redis_string.cc
Labels: bug, release notes

#338 Fix: avoid useless space allocation in SetBit
  src/redis_bitmap.cc
Labels: enhancement

#344 Fix the slave won't reconnect when failing to connect with master
  src/replication.cc
Labels: bug, need back patch, release notes

#347 Fix master pauses synchronizing with replicas
  src/redis_list.cc
  src/replication.cc
  src/replication.h
  tests/tcl/tests/integration/replication.tcl
Labels: bug, release notes
