Repository apache/kvrocks, pull requests merged in 2021-06, with the labels that each got.

#289 Support the auto-resize-block-and-sst config directive
  kvrocks.conf
  src/config.cc
  src/config.h
  src/server.cc
  src/server.h
Labels: bug, need back patch, release notes

#294 Auto resize rocksdb.block_size in autoResizeBlockAndSST
  kvrocks.conf
  src/server.cc
Labels: release notes

#285 Support transaction
  docs/support-commands.md
  src/redis_cmd.cc
  src/redis_cmd.h
  src/redis_connection.cc
  src/redis_connection.h
  src/redis_request.cc
  src/redis_request.h
  tests/tcl/tests/test_helper.tcl
  tests/tcl/tests/unit/command.tcl
  tests/tcl/tests/unit/multi.tcl
Labels: major decision, release notes

#298 Fix zset add the same member with different scores
  src/redis_zset.cc
  tests/tcl/tests/unit/type/zset.tcl
Labels: bug, need back patch, release notes

#291 Encode key with slot id
  CMakeLists.txt
  kvrocks.conf
  src/Makefile
  src/compact_filter.cc
  src/config.cc
  src/config.h
  src/encoding.cc
  src/encoding.h
  src/redis_bitmap.cc
  src/redis_cmd.cc
  src/redis_db.cc
  src/redis_db.h
  src/redis_hash.cc
  src/redis_list.cc
  src/redis_metadata.cc
  src/redis_metadata.h
  src/redis_set.cc
  src/redis_slot.cc
  src/redis_slot.h
  src/redis_sortedint.cc
  src/redis_zset.cc
  src/storage.cc
  src/storage.h
  tests/compact_test.cc
  tests/config_test.cc
  tests/tcl/tests/assets/default.conf
  tests/tcl/tests/helpers/crc16_slottable.tcl
  tests/tcl/tests/test_helper.tcl
  tests/tcl/tests/unit/cluster.tcl
  tests/tcl/tests/unit/command.tcl
  tests/tcl/tests/unit/keyspace.tcl
  tests/tcl/tests/unit/scan.tcl
  tests/tcl/tests/unit/type/sint.tcl
Labels: major decision, release notes

#300 Add source code overview doc
  docs/source-code-overview.CN.md
Labels: documentation
