Repository apache/kvrocks, pull requests merged in 2021-04, with the labels that each got.

#217 Remove codis support
  CMakeLists.txt
  README.md
  kvrocks.conf
  src/Makefile
  src/compact_filter.cc
  src/compact_filter.h
  src/compaction_checker.cc
  src/compaction_checker.h
  src/config.cc
  src/config.h
  src/redis_bitmap.cc
  src/redis_bitmap.h
  src/redis_cmd.cc
  src/redis_db.cc
  src/redis_db.h
  src/redis_slot.cc
  src/redis_slot.h
  src/server.cc
  src/server.h
  src/storage.cc
  src/storage.h
  tests/config_test.cc
  tools/kvrocks2redis/parser.cc
Labels: major decision, release notes

#221 Fix get corruption writebatch data after psync restart
  src/replication.cc
Labels: bug, need back patch, release notes

#229 Fix rocksdb can't auto resume after no space error
  src/event_listener.cc
  src/server.cc
  src/storage.h
Labels: bug, need back patch, release notes

#232 Use checkpoint to implement kvrocks backup
  kvrocks.conf
  src/config.cc
  src/config.h
  src/replication.cc
  src/server.cc
  src/storage.cc
  src/storage.h
Labels: major decision, release notes

#233 Replicas can empty db before full synchronization
  kvrocks.conf
  src/config.cc
  src/config.h
  src/replication.cc
  src/server.cc
  src/server.h
  src/storage.cc
  src/storage.h
Labels: major decision, release notes

#236 Fix uninitialized Rocksdb.level0_stop_writes_trigger
  kvrocks.conf
  src/Makefile
  src/config.cc
  tests/config_test.cc
Labels: need back patch, release notes
