Repository apache/kvrocks, pull requests merged in 2022-01, with the labels that each got.

#375 Support executing INFO command during restoring database
  src/redis_cmd.cc
  src/server.cc
Labels: need tests

#436 Allow to disable jemalloc when compiling
  .github/workflows/run-ci-without-jemalloc.yaml
  CMakeLists.txt
  cmake/rocksdb.cmake
  src/Makefile
Labels: run ci without jemalloc

#446 Fix failing full replication when enabling slave-empty-db-before-fullsync
  src/config.cc
  src/config.h
  src/replication.cc
  src/storage.cc
  tests/tcl/tests/integration/replication.tcl
Labels: bug, release notes

#461 Fix memory leak when full replication
  src/replication.cc
Labels: bug, release notes

#463 Support CLUSTERX SETSLOT command
  .gitignore
  src/cluster.cc
  src/cluster.h
  src/redis_cmd.cc
  tests/tcl/tests/integration/cluster.tcl
Labels: release notes, cluster

#465 Fix the bitmap range is smaller than that of Redis
  src/redis_bitmap.cc
  src/redis_bitmap.h
  src/redis_bitmap_string.cc
  src/redis_bitmap_string.h
  src/redis_cmd.cc
  tests/t_bitmap_test.cc
  tests/tcl/tests/unit/type/bitmap.tcl
  tests/tcl/tests/unit/type/string.tcl
Labels: bug, release notes
