Repository apache/kvrocks, pull requests merged in 2022-03, with the labels that each got.

#506 Fix wrong replication state
  src/replication.cc
Labels: bug, release notes

#497 Add dynamically adjust the upper limit of the data that each layer configure option.
  .gitignore
  kvrocks.conf
  src/config.cc
  src/config.h
  src/storage.cc
  tests/config_test.cc
Labels: new feature

#503 Fix blob file size unit error and default value error.
  kvrocks.conf
  src/config.cc
  src/storage.cc
  tests/config_test.cc
Labels: bug

#515 fix: return bulk string (instead of array) when spop without count.
  src/redis_cmd.cc
Labels: bug

#518 Fix rocksdb cmake depends should use list instead of string
  README.md
  cmake/rocksdb.cmake
Labels: bug

#471 Support BITOP command
  src/batch_extractor.cc
  src/redis_bitmap.cc
  src/redis_bitmap.h
  src/redis_cmd.cc
  src/redis_metadata.h
  tests/tcl/tests/unit/command.tcl
  tests/tcl/tests/unit/type/bitmap.tcl
Labels: enhancement, new feature, release notes
