Repository apache/kvrocks, pull requests merged in 2022-05, with the labels that each got.

#531 Add support for listening to unix socket
  kvrocks.conf
  src/config.cc
  src/config.h
  src/config_type.h
  src/redis_cmd.cc
  src/scripting.cc
  src/server.cc
  src/util.cc
  src/util.h
  src/worker.cc
  src/worker.h
Labels: new feature, release notes

#550 Refactoring Dockerfile
  .dockerignore
  .github/workflows/daily-ci.yaml
  .github/workflows/release.yaml
  Dockerfile
Labels: enhancement, compile

#554 Support to listen on ipv6 address
  kvrocks.conf
  src/util.cc
  src/worker.cc
Labels: enhancement, new feature

#586 Refactor CMakeLists: introduce target `kvrocks_objs` to avoid redundance
  CMakeLists.txt
  build.sh
Labels: enhancement, release notes

#577 Add LMove command
  src/lock_manager.cc
  src/lock_manager.h
  src/redis_cmd.cc
  src/redis_list.cc
  src/redis_list.h
  src/redis_metadata.h
  tests/rwlock_test.cc
  tests/t_list_test.cc
  tests/tcl/tests/unit/command.tcl
  tests/tcl/tests/unit/type/list.tcl
Labels: new feature, release notes

#538 PSYNC based on Unique Replication Sequence ID
  kvrocks.conf
  src/batch_extractor.cc
  src/config.cc
  src/config.h
  src/redis_cmd.cc
  src/replication.cc
  src/replication.h
  src/server.cc
  src/server.h
  src/storage.cc
  src/storage.h
  tests/tcl/tests/integration/rsid_psync.tcl
  tests/tcl/tests/test_helper.tcl
Labels: bug, release notes, major decision

#606 Fix the slave may crash when restoring the db
  src/server.cc
Labels: bug, release notes

#594 Add optional parameter to LPOP/RPOP to pop more than 1 element
  src/redis_cmd.cc
  src/redis_list.cc
  src/redis_list.h
  tests/t_list_test.cc
  tests/tcl/tests/unit/type/list.tcl
Labels: enhancement, release notes

#613 Allow to send logs to stdout/stderr
  cmake/glog.cmake
  cmake/snappy.cmake
  kvrocks.conf
  src/main.cc
Labels: new feature, release notes
