Repository apache/kvrocks, pull requests merged in 2023-07, with the labels that each got.

#1558 Avoid printing the invalid configuration key when loading namespaces
  src/config/config.cc
Labels: need-cherry-pick

#1548 Fix plain GETEX wrongly removing expiration time
  src/commands/cmd_string.cc
  src/types/redis_string.cc
  src/types/redis_string.h
  tests/gocase/unit/type/strings/strings_test.go
Labels: need-cherry-pick

#1568 Fix EVAL crashing server when numkeys is -1
  src/commands/cmd_script.cc
  tests/gocase/unit/scripting/scripting_test.go
Labels: security, scripting

#1566 Add used-after-move checking to clang-tidy
  .clang-tidy
  src/storage/compaction_checker.cc
Labels: A-ci

#1569 Add container environment for building and testing in CI
  .github/workflows/kvrocks.yaml
Labels: A-ci

#1570 Make INFO command reject cases with arguments greater than 2
  src/commands/cmd_server.cc
Labels: server

#1562 Fix EXEC / DISCARD without MULTI wrongly reset watch
  src/commands/cmd_txn.cc
  tests/gocase/unit/multi/multi_test.go
Labels: fix, transaction

#1593 Fix ZRANGESTORE arity -4 crash the server
  src/commands/cmd_zset.cc
  tests/gocase/unit/type/zset/zset_test.go
Labels: security, fix

#1592 Add the support of BLMOVE
  src/commands/cmd_list.cc
  tests/gocase/unit/type/list/list_test.go
Labels: new-command

#1565 Add the support of the HRANDFIELD command
  src/commands/cmd_hash.cc
  src/types/redis_hash.cc
  src/types/redis_hash.h
  tests/cppunit/types/hash_test.cc
  tests/gocase/unit/type/hash/hash_test.go
Labels: new-command
