Repository apache/kvrocks, pull requests merged in 2023-03, with the labels that each got.

#1279 Support watch/unwatch commands
  src/commands/cmd_list.cc
  src/commands/cmd_script.cc
  src/commands/cmd_stream.cc
  src/commands/cmd_txn.cc
  src/commands/commander.cc
  src/commands/commander.h
  src/server/redis_connection.cc
  src/server/redis_connection.h
  src/server/server.cc
  src/server/server.h
  src/server/worker.cc
  tests/gocase/unit/multi/multi_test.go
Labels: new feature

#1342 Implement the new encoding with 64bit size and expire time in milliseconds
  .github/workflows/kvrocks.yaml
  CMakeLists.txt
  src/cluster/slot_migrate.cc
  src/commands/cmd_key.cc
  src/commands/cmd_string.cc
  src/commands/ttl_util.h
  src/storage/batch_extractor.cc
  src/storage/compact_filter.cc
  src/storage/redis_db.cc
  src/storage/redis_db.h
  src/storage/redis_metadata.cc
  src/storage/redis_metadata.h
  src/types/redis_bitmap.cc
  src/types/redis_bitmap_string.cc
  src/types/redis_hash.cc
  src/types/redis_string.cc
  src/types/redis_string.h
  tests/cppunit/types/hash_test.cc
  tests/cppunit/types/metadata_test.cc
  tests/cppunit/types/string_test.cc
  tests/gocase/unit/expire/expire_test.go
  utils/kvrocks2redis/parser.cc
  utils/kvrocks2redis/parser.h
Labels: feature, major decision, A-build

#1345 Fix missing stream increment batch in cluster migration
  src/cluster/slot_migrate.cc
  src/storage/batch_extractor.cc
  src/storage/batch_extractor.h
  src/types/redis_stream.cc
  tests/gocase/integration/slotmigrate/slotmigrate_test.go
Labels: bug, A-cluster

#1325 Allow to configure the compaction checker policy
  kvrocks.conf
  src/config/config.cc
  src/config/config.h
  src/server/server.cc
  src/storage/compaction_checker.cc
  src/storage/storage.h
Labels: enhancement
